### Add Company
POST http://localhost:8080/company
Content-Type: application/json

{
  "ticker": "MMM"
}


### Get All companies info
GET http://localhost:8080/company


### Get All company dividend
GET http://localhost:8080/finance/dividend/3M Company


### Get autocomplete
GET http://localhost:8080/company/autocomplete?keyword=I